### ISSUE TITLE
Need to upload text using file uploads.  Typing is too clunky.  Interface is too small

### ISSUE THREAD

**Issue by richlysakowski** [RaffaeleFiorillo/Fast_and_Curious#4]
I provided an English translation of the documentation. 

I need to just put text into a file and have it load into the game.  Typing in custom text is too clunky.  Interface is too small.  Please fix this.  It is not scalable for longer text. 

Also, Text is currently saved in encrypted form, which is unnecessary.  

Also, Please provide instructions for how to make changes and recompile the game.

Thank you.

**Comment by RaffaeleFiorillo** [comment]
Yes. Some versions ago it was better. I am working on improving the typing mechanics. I have already a lot work (locally), ahead of this repository like an upgrade of FPS, new menus, improved HUD (easier to read and play) and other interesting stuff. But I have been working on a lot of other projects and haven't got the time to finish the upgrades. I will go back to working on the game as soon as I can.

**Comment by RaffaeleFiorillo** [comment]
# How to Change and recompile the game:
The game is made using python, with the help of the pygame library. I create the executable using pyinstaller. Right now pyinstaller is used with the command prompt, but I am working on a GUI version of it in this exact moment. You can find the repository of the "game compiler" here: https://github.com/RaffaeleFiorillo/APPythonix.

# Why the texts are encrypted:
The texts are encrypted with a self made algorithm and there is a reason for their encryption: There is a specific set of rules for the texts used in the game (rules of size and valid characters). By having  the texts encrypted, players are discouraged to alter them. Instead, the game provides a way to introduce new texts in the game. I would use this tool to introduce new texts.
